### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by berndporr** [nathanLoretan/FIR_Filter#1]
Great work. Can you change it to Python 3? That would be very much appreciated.
[FIR_filter.zip](https://github.com/nathanLoretan/FIR_Filter/files/1565132/FIR_filter.zip)
Subdir with the Python3 Makefile attached.

**Comment by nathanLoretan** [comment]
I change the Makefile. It is possible to compile using python3 with `$ make python3` or `$ make` and to  compile with python2.7 using `$ make python2.7`.
